plugins = []
headers = []
# Site ID
[site]
  id = "6df47b6f-6792-4a74-8bb0-e2f4c41d2651"

# Build settings
[build]
  # This should be relative to your project root!
  publish = "dist"  # or "build" or whatever your build folder is
  command = "npm run build"

# Add some redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]

[functions."*"]

[build]
publish = "/Users/gabrielmajorsky/Documents/__________win10dev.xyz/zzzzzzzzzz_game-source-code/igiteam.github.com/macosxjs"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]