plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/gabrielmajorsky/Documents/__________win10dev.xyz/zzzzzzzzzz_game-source-code/igiteam.github.com/macosxjs"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]