#!/bin/bash
set -e

# Generated by Project Packager
# Tue Dec 16 15:36:29 GMT 2025

# ============================================
# Project Installation Script
# Generated: 2026-02-03 20:54:51
# Source: src
# ============================================

# SAFETY CHECK - Only create files, don't execute anything
if [ "$1" != "--extract-only" ]; then
    echo "Usage: $0 --extract-only"
    echo "This script only extracts files, doesn't build or execute them."
    echo "Run with: $0 --extract-only"
    exit 1
fi

echo "📦 Project Packager v1.0"
echo "========================="
echo ""

# Create directory structure
echo "📁 Creating directories..."
mkdir -p "apps"
mkdir -p "components"
echo ""

# Create files
echo "📄 Creating files..."
# apps/AppStore.js (829 bytes)
cat <<EOL > "apps/AppStore.js"
import * as React from "react";
import FaceTime from "./FaceTime";
import Terminal from "./Terminal";
import Safari from "./Safari";
import TextEditor from "./TextEditor";

export const apps = [
  {
    title: "Finder",
    icon: "finder"
  },
  {
    title: "Safari",
    icon: "safari",
    content: () => <Safari />
  },
  {
    title: "Terminal",
    icon: "terminal",
    content: () => <Terminal />
  },
  {
    title: "FaceTime",
    icon: "facetime",
    content: () => <FaceTime />
  },
  {
    title: "TextEdit",
    icon: "notes",
    content: () => <TextEditor />
  },
  {
    title: "Calculator",
    icon: "calculator",
    content: () => "App to be delivered soon"
  },
  {
    title: "AppStore",
    icon: "appstore",
    content: () => "App to be delivered soon"
  }
];

EOL

# apps/FaceTime.js (1.8 KB)
cat <<EOL > "apps/FaceTime.js"
import React, {useState,useRef} from "react";
import Webcam from "react-webcam";

const videoConstraints = {
  facingMode: "user"
};


export default function FaceTime() {
  const webcamRef = useRef(null);
  const [imgSrc, setImgSrc] = useState(null);
  const [click, setClick] = useState(false);
  const capture = React.useCallback(
    () => {
      const imageSrc = webcamRef.current.getScreenshot();
      setImgSrc(imageSrc);
    },
    [webcamRef,setImgSrc]
  );
  if(click)
    return(
      <div id="container" className="border-8 bg-gray-800 h-full flex space-y-6 flex-col justify-center items-center">
        {imgSrc && (
          <img className="max-h-60 md:max-h-96" src={imgSrc} alt="yourimage"/>
        )}
        <button 
        style={{
          borderWidth:1,
          borderColor:'rgba(0,0,0,0.5)',
          alignItems:'center',
          justifyContent:'center',
          width:75,
          height:25,
          backgroundColor:'#fff',
          borderRadius:50
        }}
        className={\\`mx-auto\\`} onClick={() => { setClick(false); }}><b>Retake</b></button>
      </div>
    );
  else
    return (
      <div id="container" className="bg-gray-800 h-full flex space-y-6 flex-col justify-center items-center">
        <Webcam className="border-8 max-h-60 md:max-h-96"
          audio={false}
          ref={webcamRef}
          screenshotFormat="image/jpeg"
          videoConstraints={videoConstraints}
        />
        <button 
        style={{
          borderWidth:1,
          borderColor:'rgba(0,0,0,0.5)',
          alignItems:'center',
          justifyContent:'center',
          width:50,
          height:50,
          backgroundColor:'#fff',
          borderRadius:50
        }}
        className={\\`mx-auto\\`} onClick={() => { setClick(true); capture();}}></button>
      </div>
  );
}

EOL

# apps/Safari.js (653 bytes)
cat <<EOL > "apps/Safari.js"
import React, { useState } from "react";

export default function Safari() {
  const [currentUrl, setCurrentUrl] = useState("https://www.worldometers.info/coronavirus/");

  return (
    <div className="w-full h-full">
      <div className="h-8 flex justify-center items-center bg-gray-300">
        <input
          type="text"
          value={currentUrl}
          onChange={(e) => setCurrentUrl(e.target.value)}
          className="h-6 w-4/5 p-2 rounded text-center font-semibold"
        />
      </div>
      <iframe title={"Safari clone browser"} src={currentUrl} frameborder="0" className="h-full w-full"/>
    </div>
  );
}

EOL

# apps/Terminal.js (1.2 KB)
cat <<EOL > "apps/Terminal.js"
import React, { useState } from "react";

export default function Terminal() {
  const [inputValue, setInputValue] = useState("");
  const [bufferval, setBufferval] = useState([]);

  const evaluate = (e) => {
    const keyCode = e.which || e.keyCode;
    var output = "Error: Check your syntax";
    if (keyCode === 13) {
      // Enter pressed
      try {
        output = eval(inputValue);
      } catch (e) {
        if (e instanceof SyntaxError) {
          output = e.message;
        }
      }
      setBufferval([...bufferval, "\\$ " + inputValue, "> " + output]);

      setInputValue("");

      return false;
    }
  };

  return (
    <div className="w-full h-full bg-black text-white">
      <div className="w-full h-max pt-2 px-1.5 ">
        <span className="text-green-300">ヽ(ˋ▽ˊ)ノ</span>: Hey, you found the
        terminal ! Type below to get started :)
      </div>
      {bufferval.map((t) => (
        <p className="font-mono">{t}</p>
      ))}
      <input
        type="text"
        value={"\\$ " + inputValue}
        onChange={(e) => setInputValue(e.target.value.substring(2))}
        onKeyPress={evaluate}
        className="w-full bg-black text-white font-mono"
      />
    </div>
  );
}

EOL

# apps/TextEditor.js (793 bytes)
cat <<EOL > "apps/TextEditor.js"
import React, {useRef, useEffect} from "react";

export default function TextEditor() {
  const textareaRef = useRef(null)

  const contentValue = \\`
   _          _ _
  | |__   ___| | | ___
  | '_ \\\\ / _ | | |/ _ \\\\
  | | | |  __| | | (_) |
  |_| |_|\\\\___|_|_|\\\\___/
  
                      _     _
  __      _____  ____| | __| |
  \\\\ \\\\ /\\\\ / / _ \\\\| ___| |/ _  |
   \\\\ V  V | (_) | |  | | (_| |
    \\\\_/\\\\_/ \\\\___/|_|  |_|\\\\____| \\`

  useEffect(() => {
    textareaRef.current.textContent = contentValue
    textareaRef.current.focus()
  }, [textareaRef, contentValue])

  return (
    <div className="w-full h-full bg-grey">
      <textarea
        ref={textareaRef}
        type="text"
        className="h-full w-full font-mono"
      />
    </div>
  );
}
EOL

# components/ControlCenterMenu.js (5.5 KB)
cat <<EOL > "components/ControlCenterMenu.js"
import React from "react";
import * as Icon from "react-feather";
import Slider from "react-rangeslider";
import "react-rangeslider/lib/index.css";

const SliderComponent = ({ icon, value, setValue }) => {
  return (
    <div className="slider flex flex-row w-full">
      <div className="h-8 p-2 bg-white rounded-l-full">{icon}</div>
      <Slider
        min={20}
        max={100}
        value={value}
        tooltip={false}
        orientation="horizontal"
        onChange={(v) => setValue(v)}
      />
    </div>
  );
};

export default function ControlCenterMenu({
  play,
  pause,
  playing,
  setplaying,
  bluetooth,
  setbluetooth,
  wifi,
  setwifi,
  brightness,
  setbrightness,
  volume,
  setVolume
}) {
  return (
    <div className="fixed top-8 right-2 z-50 p-2 grid grid-cols-4 grid-rows-5 gap-2 bg-white bg-opacity-25 blur rounded-2xl text-black shadow-2xl ccm">
      <div className="row-span-2 col-span-2 bg-white bg-opacity-50 rounded-xl p-2 flex flex-col justify-around">
        <div className="flex flex-row items-center space-x-2 pr-6">
          {wifi === false && (
            <Icon.Wifi
              color="black"
              size={36}
              className="bg-white bg-opacity-50 rounded-full p-2"
              onClick={() => {
                setwifi(true);
              }}
            />
          )}
          {wifi === true && (
            <Icon.Wifi
              color="white"
              size={36}
              className="bg-blue-500 rounded-full p-2"
              onClick={() => {
                setwifi(false);
              }}
            />
          )}
          <div className="flex flex-col">
            <span className="font-medium">Wifi</span>
            <span className="font-thin text-xs">Home</span>
          </div>
        </div>
        <div className="flex flex-row items-center space-x-2 pr-6">
          {bluetooth === false && (
            <Icon.Bluetooth
              color="black"
              size={36}
              className="bg-white bg-opacity-50 rounded-full p-2"
              onClick={() => {
                setbluetooth(true);
              }}
            />
          )}
          {bluetooth === true && (
            <Icon.Bluetooth
              color="white"
              size={36}
              className="bg-blue-500 rounded-full p-2"
              onClick={() => {
                setbluetooth(false);
              }}
            />
          )}
          <div className="flex flex-col">
            <span className="font-medium">Bluetooth</span>
          </div>
        </div>
        <div className="flex flex-row items-center space-x-2 pr-6">
          <Icon.Rss
            color="white"
            size={36}
            className="bg-blue-500 rounded-full p-2"
          />
          <div className="flex flex-col">
            <span className="font-medium">AirDrop</span>
            <span className="font-thin text-xs">Contacts Only</span>
          </div>
        </div>
      </div>
      <div className="col-span-2 bg-white bg-opacity-50 blur rounded-xl p-2 flex flex-row items-center space-x-2">
        <Icon.Moon
          size={36}
          fill
          className="bg-white bg-opacity-50 rounded-full p-2"
        />
        <div className="flex flex-col">
          <span className="font-medium">Do Not Disturb</span>
        </div>
      </div>
      <div className="bg-white bg-opacity-50 blur rounded-xl p-2 flex flex-col justify-center items-center text-center">
        <Icon.Sun />
        <span className="text-xs">Keyboard Brightness</span>
      </div>
      <div className="bg-white bg-opacity-50 blur rounded-xl p-2 flex flex-col justify-center items-center text-center">
        <Icon.Monitor />
        <span className="text-xs">Airplay Display</span>
      </div>
      <div className="col-span-4 bg-white bg-opacity-50 blur rounded-xl p-2 space-y-2 flex flex-col justify-around">
        <span className="font-medium">Display</span>
        <SliderComponent
          icon={<Icon.Sun size={16} className="text-gray-500" />}
          value={brightness}
          setValue={setbrightness}
        />
      </div>
      <div className="col-span-4 bg-white bg-opacity-50 blur rounded-xl p-2 space-y-2 flex flex-col justify-around">
        <span className="font-medium">Sound</span>
        <SliderComponent
          icon={<Icon.Volume2 size={16} className="text-gray-500" />}
          value={volume}
          setValue={setVolume}
        />
      </div>
      <div className="col-span-4 bg-white bg-opacity-50 blur rounded-xl p-2 pr-4 flex flex-row justify-between items-center space-x-4">
        <img
          src="https://i1.sndcdn.com/artworks-000596249969-hovmmz-t500x500.jpg"
          alt="cover art"
          className="w-16 rounded-lg"
        />
        <div className="flex flex-col flex-grow justify-start">
          <span className="font-medium">SAINt JHN</span>
          <span className="font-extralight">Roses (Imanbek Remix)</span>
        </div>
        {playing === false && (
          <Icon.Play
            fill
            onClick={() => {
              setplaying(true);
              play();
            }}
          />
        )}
        {playing === true && (
          <Icon.Pause
            fill
            onClick={() => {
              setplaying(false);
              pause();
            }}
          />
        )}
      </div>
    </div>
  );
}

EOL

# components/Desktop.js (1.7 KB)
cat <<EOL > "components/Desktop.js"
import React, { useState } from "react";

import MenuBar from "./MenuBar";
import WindowArea from "./WindowArea";
import Dock from "./Dock";
import ControlCenterMenu from "./ControlCenterMenu";
import useSound from "use-sound";
const soundUrl = "Roses.mp3";

export default function Desktop() {
  const [showControlCenter, setShowControlCenter] = useState(false);
  const [currentApp, setCurrentApp] = useState(null);
  const [playing, setplaying] = React.useState(false);
  const [bluetooth, setbluetooth] = React.useState(true);
  const [wifi, setwifi] = React.useState(true);
  const [volume, setVolume] = React.useState(75);
  const [play, { pause }] = useSound(soundUrl, { volume: volume / 100 });
  const [brightness, setbrightness] = useState(100);
  return (
    <div
      className="w-screen h-screen overflow-hidden bg-center bg-cover"
      style={{
        backgroundImage: "url(londonview.jpg)",
        filter: \\`brightness( \\${brightness}% )\\`
      }}
    >
      <MenuBar
        title={currentApp?.title ?? "Finder"}
        showControlCenter={showControlCenter}
        setShowControlCenter={setShowControlCenter}
      />
      {showControlCenter && (
        <ControlCenterMenu
          play={play}
          pause={pause}
          playing={playing}
          setplaying={setplaying}
          bluetooth={bluetooth}
          setbluetooth={setbluetooth}
          wifi={wifi}
          setwifi={setwifi}
          brightness={brightness}
          setbrightness={setbrightness}
          volume={volume}
          setVolume={setVolume}
        />
      )}
      <WindowArea currentApp={currentApp} setCurrentApp={setCurrentApp} />
      <Dock setCurrentApp={setCurrentApp} />
    </div>
  );
}

EOL

# components/Dock.js (899 bytes)
cat <<EOL > "components/Dock.js"
import React from "react";

import { apps } from "../apps/AppStore";

export default function Dock({ setCurrentApp }) {
  const [availableApps] = React.useState(apps);

  return (
    <div className="dock w-full pb-2 fixed bottom-0">
      <ul className="osx-dock dock-item mx-auto w-max p-1 space-x-2 flex flex-row justify-center justify-between bg-white bg-opacity-25 blur rounded-2xl shadow-2xl">
        {availableApps.map((app) => (
          <li
            key={app.title}
            onClick={() => app.title !== "Finder" && setCurrentApp(app)}
          >
            {" "}
            <span className="rounded-md">{app.title}</span>
            <img
              className="w-14"
              src={\\`icons/\\${app.icon}.png\\`}
              alt={app.title}
              title={app.title}
            />
          </li>
        ))}
      </ul>
    </div>
  );
}

EOL

# components/Login.js (3.4 KB)
cat <<EOL > "components/Login.js"
import React, { useState } from "react";
import { BsArrow90DegRight } from "react-icons/bs";
import { CgSleep } from "react-icons/cg";
import { RiShutDownLine, RiRestartLine } from "react-icons/ri";
const Style1 = {
  height: "100vh",
  width: "100vw",
  background: "url(abc.jpg) center/cover no-repeat"
};
const Style2 = {
  height: "100vh",
  width: "100vw",
  background: "url(ls.jpg) center/cover no-repeat"
};

export default function Login({ setlogon }) {
  const [bgblur, setbgblur] = useState(false);

  if (!bgblur) {
    return <div style={Style1} onClick={() => setbgblur(true)} />;
  } else {
    return (
      <div style={Style2}>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh"
          }}
        >
          <div
            className="Box"
            onClick={() => {
              setlogon(true);
            }}
          >
            <div className="inline-block w-auto relative top-1/2 -mt-40">
              {/* Avatar */}
              <img
                className="rounded-full w-24 h-24 my-0 mx-auto"
                src="profileimg.png"
                alt="img"
              />
              <div className="font-semibold text-xl mt-2 ml-10 text-white">
                Macintosh
              </div>

              {/* Password Input */}
              <div className="mx-auto grid grid-cols-5 w-44 h-8 mt-4 rounded-md bg-gray-300 blur bg-opacity-50">
                <input
                  className="text-sm col-start-1 col-span-4 outline-none focus:outline-none px-2 "
                  type="password"
                  placeholder="Enter Password"
                  onClick={(e) => e.stopPropagation()}
                  onKeyPress={this.keyPress}
                />
                <div className="col-start-5 col-span-1 flex justify-center items-center">
                  <BsArrow90DegRight className="ml-1" color="white" />
                </div>
              </div>

              <div className="nightwind-prevent text-sm mt-2 ml-10 text-gray-200">
                Click to enter
              </div>
            </div>
          </div>
          <div className="nightwind-prevent-block text-sm fixed bottom-16 left-0 right-0 mx-auto flex flex-row space-x-4 w-max">
            <div className="flex flex-col items-center text-white w-24">
              <div className="h-10 w-10 bg-gray-700 rounded-full inline-flex justify-center items-center">
                <CgSleep size={40} />
              </div>
              <span>Sleep</span>
            </div>
            <div
              className="flex flex-col items-center text-white w-24"
              onClick={() => {
                setbgblur(false);
              }}
            >
              <div className="h-10 w-10 bg-gray-700 rounded-full inline-flex justify-center items-center">
                <RiRestartLine size={36} />
              </div>
              <span>Restart</span>
            </div>
            <div className="flex flex-col items-center text-white w-24">
              <div className="h-10 w-10 bg-gray-700 rounded-full inline-flex justify-center items-center">
                <RiShutDownLine size={36} />
              </div>
              <span>Shut Down</span>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

EOL

# components/MenuBar.js (2.0 KB)
cat <<EOL > "components/MenuBar.js"
import React, { useEffect, useState } from "react";
import format from "date-fns/format";

function MenuItem({ children }) {
  return (
    <div className="inline-flex flex-row space-x-1 hover:bg-white hover:bg-opacity-50 rounded p-1">
      {children}
    </div>
  );
}

export default function MenuBar({
  title,
  showControlCenter,
  setShowControlCenter
}) {
  // const [showControlCenter, setShowControlCenter] = useState(false);
  const [date, setDate] = useState(new Date());

  useEffect(() => {
    let timer = setTimeout(() => setDate(new Date()), 60 * 1000);
    return () => clearTimeout(timer);
  }, [date]);

  return (
    <div className="w-full h-6 px-4 fixed top-0 flex flex-row justify-between items-center text-sm text-white bg-indigo-900 bg-opacity-25 blur shadow transition">
      <div className="flex flex-row items-center space-x-4">
        <img
          className="h-4 filter-invert"
          src="menuicons/Apple.png"
          alt="apple_icon"
        />
        <span className="font-semibold">{title}</span>
      </div>
      <div className="flex flex-row justify-end items-center space-x-2">
        <MenuItem>
          <span className="text-xs">100%</span>
          <img
            className="h-4 filter-invert"
            src="menuicons/battery.100.png"
            alt="battery"
          />
        </MenuItem>
        <MenuItem>
          <img
            className="h-4 filter-invert"
            src="menuicons/magnifyingglass.png"
            alt="search"
          />
        </MenuItem>
        <MenuItem>
          <img
            className="w-4 h-4 filter-invert"
            src="menuicons/controlcenter.png"
            alt="control center"
            onClick={() => setShowControlCenter(!showControlCenter)}
          />
        </MenuItem>
        {/* {showControlCenter && <ControlCenterMenu />} */}
        <span>{format(date, "eee d MMM h:mm aa")}</span>
      </div>
    </div>
  );
}

EOL

echo "  Processed 10/13 files..."
# components/WindowArea.js (1.5 KB)
cat <<EOL > "components/WindowArea.js"
import React from "react";
import Draggable from "react-draggable";

function TrafficLights({ setCurrentApp, setMax, max }) {
  return (
    <div className="flex flex-row absolute left-0 space-x-2 py-1 pl-2">
      <button
        className="w-4 h-4 rounded-full bg-red-500"
        onClick={() => setCurrentApp(null)}
      />
      <button
        className="w-4 h-4 rounded-full bg-yellow-500"
        onClick={() => setMax(false)}
      />
      <button
        className="w-4 h-4 rounded-full bg-green-500"
        onClick={() => setMax(!max)}
      />
    </div>
  );
}

export default function WindowArea({ currentApp, setCurrentApp }) {
  const [max, setMax] = React.useState(false);

  const size = max ? "w-5/6 h-5/6" : "h-3/4 w-7/12 mt-16 mb-24";

  if (currentApp == null) {
    return <div />;
  }
  return (
    <Draggable>
      <div
        className={\\`transition-hw mt-6 mb-8 mx-auto rounded-lg bg-white \\${size}\\`}
      >
        <div className="relative h-6 text-center bg-gray-300 rounded-t-lg">
          <TrafficLights
            setCurrentApp={setCurrentApp}
            max={max}
            setMax={setMax}
          />
          <span className="font-semibold text-gray-700">
            {currentApp.title}
          </span>
        </div>
        <div className="abcd w-full overflow-y-hidden">
          {currentApp.content?.() ?? \\`I'm \\${currentApp.title} app\\`}
        </div>
      </div>
    </Draggable>
  );
}

EOL

# index.js (504 bytes)
cat <<EOL > "index.js"
import React, { useState } from "react";
import ReactDOM from "react-dom";
import "./styles.css";

import Desktop from "./components/Desktop";
import Login from "./components/Login";

export default function App() {
  const [logon, setlogon] = useState(false);

  if (logon) {
    return <Desktop />;
  } else {
    return <Login setlogon={setlogon} />;
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  rootElement
);

EOL

# styles.css (1.4 KB)
cat <<EOL > "styles.css"
* {
  margin: 0;
  padding: 0;
}

.font-mono {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
    "Liberation Mono", "Courier New", monospace !important;
}

html,
body {
  height: 100%;
}

.ccm {
  grid-template-columns: repeat(4, 5rem);
  grid-template-rows: repeat(5, 5rem);
}

.blur {
  backdrop-filter: blur(48px);
}

.transition-hw {
  transition-property: height, width;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 0.5s;
}

.filter-invert {
  filter: invert();
}

.abcd {
  height: calc(100% - 1.5rem);
}
/* slider */

.slider .rangeslider {
  margin: 0 !important;
  width: 100%;
  height: 2rem;
  background-color: rgba(0, 0, 0, 0.1);
  border-radius: 9999px;
  box-shadow: none;
}
.slider .rangeslider .rangeslider__fill {
  background-color: #fff;
  box-shadow: none;
  border-radius: 0;
}
.slider .rangeslider .rangeslider__handle {
  background-color: #fff;
  color: #fff;
  box-shadow: -5px 0px 10px 0px rgba(17, 17, 17, 0.2);
  border: none;
  outline: none;
}
.slider .rangeslider .rangeslider__handle::after {
  display: none;
}

ul.osx-dock li span {
  background: rgba(0, 0, 0, 0.75);
  font-size: 12px;
  position: absolute;
  bottom: 80px;
  margin: 0 auto;
  display: none;
  padding: 3px 6px;
  color: #fff;
}
ul.osx-dock li:hover span {
  display: block;
}

EOL

echo ""
# Display statistics
echo "✅ Project successfully recreated!"
echo "📊 Statistics:"
echo "   • Directories: 2"
echo "   • Files: 13"
echo "   • Skipped: 0"
echo "   • Total size: 0.0 MB"
echo "🏠 Location: $(pwd)"
echo "🚀 Ready to use!"

# End of script

echo "File List"
echo "========="
echo ""
echo "[FOLDER] components/"
echo "[JS    ] components/WindowArea.js (1.46 KiB)"
echo "[JS    ] components/ControlCenterMenu.js (5.46 KiB)"
echo "[JS    ] components/Dock.js (899.0 B)"
echo "[JS    ] components/MenuBar.js (1.96 KiB)"
echo "[JS    ] components/Login.js (3.4 KiB)"
echo "[JS    ] components/Desktop.js (1.73 KiB)"
echo "[FOLDER] apps/"
echo "[JS    ] apps/TextEditor.js (793.0 B)"
echo "[JS    ] apps/Terminal.js (1.24 KiB)"
echo "[JS    ] apps/FaceTime.js (1.85 KiB)"
echo "[JS    ] apps/Safari.js (653.0 B)"
echo "[JS    ] apps/AppStore.js (829.0 B)"
echo "[CSS   ] styles.css (1.38 KiB)"
echo "[JS    ] index.js (504.0 B)"
echo ""
echo "End of File List"